spring:
  datasource:
    driver: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/potal?&serverTimezone=UTC&autoReconnect=true&allowMultiQueries=true&characterEncoding=UTF-8
    username: energy
    password: energy
    mapper-locations: classpath:/mapper/**/*.xml

server:
  port: 8081

JWT_TOKEN: TmV0bWljcw==
JWT_EXPIRE_TIME: 86400000

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    operations-sorter: alpha # alpha(알파벳 오름차순), method(HTTP메소드순)
    tags-sorter: alpha # 태그 정렬 기준
    path: /swagger-ui.html # html 문서 접속 경로
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    doc-expansion: none # tag, operation 펼치는 방식
  paths-to-match:
    - /**